/**
 * Add Japanese display names to the artist list.
 * Usage: npx tsx scripts/addJapaneseNames.ts
 */
import * as fs from 'fs'
import * as path from 'path'

// Known English -> Japanese name mappings
const NAME_MAP: Record<string, string> = {
  'Kenshi Yonezu': '米津玄師',
  'King Gnu': 'King Gnu',
  'RADWIMPS': 'RADWIMPS',
  'OFFICIAL HIGE DANDISM': 'Official髭男dism',
  'Aimyon': 'あいみょん',
  'BUMP OF CHICKEN': 'BUMP OF CHICKEN',
  'back number': 'back number',
  'Mrs. GREEN APPLE': 'Mrs. GREEN APPLE',
  'SEKAI NO OWARI': 'SEKAI NO OWARI',
  'Aimer': 'Aimer',
  'Ryokuoushoku Shakai': '緑黄色社会',
  'ZUTOMAYO': 'ずっと真夜中でいいのに。',
  'KANA-BOON': 'KANA-BOON',
  'POLKADOT STINGRAY': 'ポルカドットスティングレイ',
  'Macaroni Empitsu': 'マカロニえんぴつ',
  'UNISON SQUARE GARDEN': 'UNISON SQUARE GARDEN',
  'SPITZ': 'スピッツ',
  'sakanaction': 'サカナクション',
  'Fujifabric': 'フジファブリック',
  'Quruli': 'くるり',
  'ASIAN KUNG-FU GENERATION': 'ASIAN KUNG-FU GENERATION',
  'the pillows': 'the pillows',
  'ELLEGARDEN': 'ELLEGARDEN',
  '10-FEET': '10-FEET',
  'SiM': 'SiM',
  'coldrain': 'coldrain',
  'MAN WITH A MISSION': 'MAN WITH A MISSION',
  'ONE OK ROCK': 'ONE OK ROCK',
  'BLUE ENCOUNT': 'BLUE ENCOUNT',
  'Ling tosite sigure': '凛として時雨',
  'ACIDMAN': 'ACIDMAN',
  'Base Ball Bear': 'Base Ball Bear',
  'ART-SCHOOL': 'ART-SCHOOL',
  'cinema staff': 'cinema staff',
  'Suchmos': 'Suchmos',
  'Nulbarich': 'Nulbarich',
  'Vaundy': 'Vaundy',
  'YOASOBI': 'YOASOBI',
  'Ado': 'Ado',
  'imase': 'imase',
  'Tani Yuuki': 'tani yuuki',
  'Fujii Kaze': '藤井 風',
  'Hitsujibungaku': '羊文学',
  'Creepy Nuts': 'Creepy Nuts',
  'Eve': 'Eve',
  'Yorushika': 'ヨルシカ',
  'Yonezu Kenshi': '米津玄師',
  'milet': 'milet',
  'Ikimonogakari': 'いきものがかり',
  'GReeeeN': 'GReeeeN',
  'SCANDAL': 'SCANDAL',
  'Perfume': 'Perfume',
  'Kyary Pamyu Pamyu': 'きゃりーぱみゅぱみゅ',
  'Hoshino Gen': '星野源',
  'Suda Masaki': '菅田将暉',
  'LiSA': 'LiSA',
  'Aiko': 'aiko',
  'Utada Hikaru': '宇多田ヒカル',
  'Sheena Ringo': '椎名林檎',
  'Hikaru Utada': '宇多田ヒカル',
  'Yuzu': 'ゆず',
  'Kobukuro': 'コブクロ',
  'Mr.Children': 'Mr.Children',
  "B'z": "B'z",
  'Southern All Stars': 'サザンオールスターズ',
  'Hirai Ken': '平井堅',
  'EXILE': 'EXILE',
  'Sandaime J SOUL BROTHERS from EXILE TRIBE': '三代目 J SOUL BROTHERS',
  'Arashi': '嵐',
  'KinKi Kids': 'KinKi Kids',
  'SMAP': 'SMAP',
  'Hey! Say! JUMP': 'Hey! Say! JUMP',
  'SixTONES': 'SixTONES',
  'Snow Man': 'Snow Man',
  'King & Prince': 'King & Prince',
  'Nogizaka46': '乃木坂46',
  'Keyakizaka46': '欅坂46',
  'Sakurazaka46': '櫻坂46',
  'Hinatazaka46': '日向坂46',
  'AKB48': 'AKB48',
  'NMB48': 'NMB48',
  'Momoiro Clover Z': 'ももいろクローバーZ',
  'Babymetal': 'BABYMETAL',
  'BABYMETAL': 'BABYMETAL',
  'Wagakki Band': '和楽器バンド',
  'amazarashi': 'amazarashi',
  'RADWIMPS': 'RADWIMPS',
  'Alexandros': '[Alexandros]',
  'frederic': 'フレデリック',
  'Frederic': 'フレデリック',
  'THE ORAL CIGARETTES': 'THE ORAL CIGARETTES',
  'go!go!vanillas': 'go!go!vanillas',
  'KEYTALK': 'KEYTALK',
  'flumpool': 'flumpool',
  'Ikimonogakari': 'いきものがかり',
  'Superfly': 'Superfly',
  'JUJU': 'JUJU',
  'Tegomass': 'テゴマス',
  'Nishino Kana': '西野カナ',
  'Daoko': 'DAOKO',
  'DAOKO': 'DAOKO',
  'YUKI': 'YUKI',
  'Chatmonchy': 'チャットモンチー',
  'NUMBER GIRL': 'NUMBER GIRL',
  'toe': 'toe',
  'LITE': 'LITE',
  'MONO': 'MONO',
  'envy': 'envy',
  'Cornelius': 'コーネリアス',
  'PIZZICATO FIVE': 'ピチカート・ファイヴ',
  'Fishmans': 'フィッシュマンズ',
  'Ogre You Asshole': 'Ogre You Asshole',
  'Gesu no Kiwami Otome.': 'ゲスの極み乙女。',
  'Gesu no Kiwami Otome': 'ゲスの極み乙女。',
  'indigo la End': 'indigo la End',
  'Yasutaka Nakata': '中田ヤスタカ',
  'CAPSULE': 'CAPSULE',
  'Mondo Grosso': 'MONDO GROSSO',
  'Kohh': 'KOHH',
  'KOHH': 'KOHH',
  'Awich': 'Awich',
  'JP THE WAVY': 'JP THE WAVY',
  'ANARCHY': 'ANARCHY',
  'Punpee': 'PUNPEE',
  'PUNPEE': 'PUNPEE',
  'Kreva': 'KREVA',
  'KREVA': 'KREVA',
  'RHYMESTER': 'RHYMESTER',
  'KICK THE CAN CREW': 'KICK THE CAN CREW',
  'Ketsumeishi': 'ケツメイシ',
  'ORANGE RANGE': 'ORANGE RANGE',
  'Sambomaster': 'サンボマスター',
  'THE BACK HORN': 'THE BACK HORN',
  'STRAIGHTENER': 'ストレイテナー',
  'MONGOL800': 'MONGOL800',
  'HY': 'HY',
  'Shonan no Kaze': '湘南乃風',
  'Sukimaswitch': 'スキマスイッチ',
  'Remioromen': 'レミオロメン',
  'GING NANG BOYZ': '銀杏BOYZ',
  'THE BLUE HEARTS': 'THE BLUE HEARTS',
  'Hi-STANDARD': 'Hi-STANDARD',
  'HUSKING BEE': 'HUSKING BEE',
  'Eastern Youth': 'eastern youth',
  'Bloodthirsty Butchers': 'bloodthirsty butchers',
  'THE YELLOW MONKEY': 'THE YELLOW MONKEY',
  'THEE MICHELLE GUN ELEPHANT': 'THEE MICHELLE GUN ELEPHANT',
  'Blankey Jet City': 'BLANKEY JET CITY',
  'GLAY': 'GLAY',
  "L'Arc~en~Ciel": "L'Arc〜en〜Ciel",
  'LUNA SEA': 'LUNA SEA',
  'X Japan': 'X JAPAN',
  'DIR EN GREY': 'DIR EN GREY',
  'the GazettE': 'the GazettE',
  'MUCC': 'ムック',
  'Malice Mizer': 'MALICE MIZER',
  'Buck-Tick': 'BUCK-TICK',
  'BUCK-TICK': 'BUCK-TICK',
  'Judy And Mary': 'JUDY AND MARY',
  'PUFFY': 'PUFFY',
  'Shishamo': 'SHISHAMO',
  'WANIMA': 'WANIMA',
  'Creep Hyp': 'クリープハイプ',
  'Sunny Day Service': 'サニーデイ・サービス',
  'Flipper\'s Guitar': "フリッパーズ・ギター",
  'Ozawa Kenji': '小沢健二',
  'Shiina Ringo': '椎名林檎',
  'Tokyo Jihen': '東京事変',
  'Kinoko Teikoku': 'きのこ帝国',
  'Shintaro Sakamoto': '坂本慎太郎',
  'cero': 'cero',
  'Suchmos': 'Suchmos',
  'Lucky Tapes': 'Lucky Tapes',
  'Nariaki Obukuro': '小袋成彬',
  'Tempalay': 'Tempalay',
  'PETROLZ': 'ペトロールズ',
  'Yogee New Waves': 'Yogee New Waves',
  'never young beach': 'never young beach',
  'D.A.N.': 'D.A.N.',
  'SIRUP': 'SIRUP',
  'ODD Foot Works': 'ODD Foot Works',
  'CHAI': 'CHAI',
  'Tricot': 'tricot',
  'tricot': 'tricot',
  'Otoboke Beaver': 'おとぼけビ〜バ〜',
  'RADIO FISH': 'RADIO FISH',
  'SHISHAMO': 'SHISHAMO',
  'sumika': 'sumika',
  'My Hair is Bad': 'My Hair is Bad',
  'tacica': 'tacica',
  'People In The Box': 'People In The Box',
  'mol-74': 'mol-74',
  'Soushi Sakiyama': '崎山蒼志',
  'Rei': 'Rei',
  'Ai Higuchi': '樋口愛',
  'wacci': 'wacci',
  'Saucy Dog': 'Saucy Dog',
  'Novelbright': 'Novelbright',
  'Yabai T-Shirts Yasan': 'ヤバイTシャツ屋さん',
  'SUPER BEAVER': 'SUPER BEAVER',
  'Fear, and Loathing in Las Vegas': 'Fear, and Loathing in Las Vegas',
  'UVERworld': 'UVERworld',
  'Nana Mizuki': '水樹奈々',
  'Kana Nishino': '西野カナ',
  'Uru': 'Uru',
  'aiko': 'aiko',
  'Tokyo Incidents': '東京事変',
  'Akina Nakamori': '中森明菜',
  'Yumi Matsutoya': '松任谷由実',
  'Namie Amuro': '安室奈美恵',
  'Ayumi Hamasaki': '浜崎あゆみ',
  'Gen Hoshino': '星野源',
  'Kazuyoshi Saito': '斉藤和義',
  'Noriyuki Makihara': '槇原敬之',
  'Tatsuro Yamashita': '山下達郎',
  'Kazumasa Oda': '小田和正',
  'Hideaki Tokunaga': '徳永英明',
  'Yosui Inoue': '井上陽水',
  'Toshinobu Kubota': '久保田利伸',
  'Masaharu Fukuyama': '福山雅治',
  'Ken Hirai': '平井堅',
  'Motohiro Hata': '秦基博',
  'ayaka': '絢香',
  'Leo Ieiri': '家入レオ',
  'KOBUKURO': 'コブクロ',
  'YUZU': 'ゆず',
  'Ai Otsuka': '大塚愛',
  'MISIA': 'MISIA',
  'Every Little Thing': 'Every Little Thing',
  'DREAMS COME TRUE': 'DREAMS COME TRUE',
  'Hello! Project': 'ハロー!プロジェクト',
  'J SOUL BROTHERS III': '三代目 J SOUL BROTHERS',
  'DA PUMP': 'DA PUMP',
  'CHAGE and ASKA': 'CHAGE and ASKA',
  'ZARD': 'ZARD',
  'DEEN': 'DEEN',
  'WANDS': 'WANDS',
  'T-BOLAN': 'T-BOLAN',
  "L'Arc-en-Ciel": "L'Arc〜en〜Ciel",
  'Janne Da Arc': 'Janne Da Arc',
  'SID': 'シド',
  'PIERROT': 'PIERROT',
  'X JAPAN': 'X JAPAN',
  'Kuroyume': '黒夢',
  'SOPHIA': 'SOPHIA',
  'JUDY AND MARY': 'JUDY AND MARY',
  'Maki Ohguro': '大黒摩季',
  'Nanase Aikawa': '相川七瀬',
  'Tomomi Kahara': '華原朋美',
  'Mai Kuraki': '倉木麻衣',
  'Mika Nakashima': '中島美嘉',
  'miwa': 'miwa',
  'Mao Abe': '阿部真央',
  'YUI': 'YUI',
  "EGO-WRAPPIN'": "EGO-WRAPPIN'",
  'LOVE PSYCHEDELICO': 'LOVE PSYCHEDELICO',
  'Shikao Suga': 'スガシカオ',
  'BONNIE PINK': 'BONNIE PINK',
  'Cocco': 'Cocco',
  'カネコアヤノ': 'カネコアヤノ',
  'ネクライトーキー': 'ネクライトーキー',
  '中島みゆき': '中島みゆき',
  '櫻坂46': '櫻坂46',
  'ヨルシカ': 'ヨルシカ',
  'TOTALFAT': 'TOTALFAT',
  "Nothing\u2019s Carved In Stone": "Nothing's Carved In Stone",
  'the band apart': 'the band apart',
  'NICO Touches the Walls': 'NICO Touches the Walls',
  "EGO-WRAPPIN\u2019": "EGO-WRAPPIN'",
}

// Read current file
const filePath = path.join(__dirname, '..', 'lib', 'JapaneseArtists.ts')
const content = fs.readFileSync(filePath, 'utf-8')

// Parse the array
const match = content.match(/export const LARGE_JAPANESE_ARTISTS = (\[[\s\S]*\])/)
if (!match) {
  console.error('Could not parse JapaneseArtists.ts')
  process.exit(1)
}

const artists = JSON.parse(match[1])
let mapped = 0
let unmapped = 0

const updated = artists.map((a: { name: string; id: string; popularity: number }) => {
  const jaName = NAME_MAP[a.name]
  if (jaName && jaName !== a.name) {
    mapped++
    return { ...a, nameJa: jaName }
  }
  unmapped++
  return a
})

const output = `export const LARGE_JAPANESE_ARTISTS = ${JSON.stringify(updated, null, 2)} as const\n`
fs.writeFileSync(filePath, output)

console.log(`Done! ${mapped} artists got Japanese names, ${unmapped} kept original.`)
console.log('Unmapped artists:')
artists.forEach((a: { name: string }) => {
  if (!NAME_MAP[a.name]) console.log(`  - ${a.name}`)
})
